import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import "./globals.css";
import Header from "./components/Header";
import ThemeProvider from "@mui/material/styles/ThemeProvider";
import StoreProvider from "./StoreProvider";
import { AppItem } from "./constants/models";
import { base_url } from "./constants/keys";
import { hearWeGoDarkTheme, hearWeGoTheme } from "./styles/theme";
import { CssBaseline, PaletteMode, createTheme, useMediaQuery } from "@mui/material";
import React from "react";
import CustomeThemeProvider from "./styles/CustomeTheme";

const roboto = Roboto({ weight: ['100', '300', '400', '500', '700', '900'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch(`${base_url}/app`);
  const app: AppItem = await res.json();
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <CustomeThemeProvider>
            <StoreProvider>
              <Header app={app}/>
              {children}
            </StoreProvider>
          </CustomeThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
