import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import "./globals.css";
import Header from "./components/Header";
import ThemeProvider from "@mui/material/styles/ThemeProvider";
import { hearWeGoTheme } from "./styles/theme";
import StoreProvider from "./StoreProvider";
import { AppItem } from "./constants/models";
import { base_url } from "./constants/keys";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch(`${base_url}/app`);
  const app: AppItem = await res.json();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <StoreProvider>
            <ThemeProvider theme={hearWeGoTheme}>
              <Header app={app}/>
              {children}
            </ThemeProvider>
          </StoreProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
